pi:
    resource: "@piBundle/Resources/config/routing.yml"
    prefix:   /PIDEV

pidev:
    resource: "@PIDEVBundle/Resources/config/routing.yml"
    prefix:   /bb
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"