<?php

namespace piBundle\Repository;

/**
 * objetTrouverPerduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class objetTrouverPerduRepository extends \Doctrine\ORM\EntityRepository
{
}
