<?php

namespace piBundle\Repository;

/**
 * VentAchatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentAchatRepository extends \Doctrine\ORM\EntityRepository
{
}
